version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run: pip install -r requirements.txt

jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - setup
      - run: python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - setup
      - run: python manage.py test taskManager

  release:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t $DOCKER_USERNAME/django.nv .
          docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - setup
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: always

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
