version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run: pip install -r requirements.txt

jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - setup
      - run: python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - setup
      - run: python manage.py test taskManager

  sonarcloud-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
         name: SonarCloud Scan
         command: | 
            sonar-scanner \
            -Dsonar.organization=syafiqibrahimshah \
            -Dsonar.projectKey=syafiqibrahimshah_django.nv \
            -Dsonar.sources=. \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.coverage.exclusions=<CoverageExclusions>

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonarcloud-scan:
          requires:
            - test
